#ifndef GAME-CONSTANTS_H_INCLUDED
#define GAME-CONSTANTS_H_INCLUDED

const int MAX_NUM = 100;
const int TOO_BIG = 10, TOO_SMALL=-10, THE_SAME = 0, JUST_CLICKED= 37, INVALID_NUMBER = -123;
const int PAUSE_TIME = 750, DELAY_TIME = 10;

#endif // GAME-CONSTANTS_H_INCLUDED
